import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { randomBytes } from "node:crypto";
import { log, setLogLevel } from "./logger.js";

export const VERSION = "0.1.2";

const OPTIONS_PATH = "/data/options.json";
const TOKEN_PATH = "/data/token";

export interface AddonConfig {
  port: number;
  apiToken: string;
  /** True when the token was generated by us instead of set by the user. */
  apiTokenGenerated: boolean;
  allowWrite: boolean;
  filterReads: boolean;
  entityAllowlist: string[];
  entityDenylist: string[];
  serviceDenylist: string[];
  /** Token injected by the Supervisor when running as an add-on. */
  supervisorToken: string | null;
  /** Dev mode outside the add-on: HA base URL and a long-lived access token. */
  devHaUrl: string | null;
  devHaToken: string | null;
}

function strArray(v: unknown): string[] {
  return Array.isArray(v) ? v.map(String).filter((s) => s.trim().length > 0) : [];
}

export function loadConfig(): AddonConfig {
  let opts: Record<string, unknown> = {};
  if (existsSync(OPTIONS_PATH)) {
    try {
      opts = JSON.parse(readFileSync(OPTIONS_PATH, "utf8"));
    } catch (e) {
      log.error(`Could not read ${OPTIONS_PATH}: ${String(e)}`);
    }
  }

  const level = setLogLevel(String(opts.log_level ?? process.env.LOG_LEVEL ?? "info"));
  log.debug(`Log level set to ${level}`);

  let apiToken = String(opts.api_token ?? process.env.MCP_API_TOKEN ?? "").trim();
  let apiTokenGenerated = false;
  if (!apiToken) {
    apiToken = bootstrapToken();
    apiTokenGenerated = true;
  }

  return {
    port: Number(process.env.MCP_PORT ?? 9583),
    apiToken,
    apiTokenGenerated,
    allowWrite: opts.allow_write === true || process.env.MCP_ALLOW_WRITE === "true",
    filterReads: opts.filter_reads === true,
    entityAllowlist: strArray(opts.entity_allowlist),
    entityDenylist: strArray(opts.entity_denylist),
    serviceDenylist: strArray(opts.service_denylist),
    supervisorToken: process.env.SUPERVISOR_TOKEN ?? null,
    devHaUrl: process.env.HA_URL ?? null,
    devHaToken: process.env.HA_TOKEN ?? null,
  };
}

/**
 * No token configured: generate a random one (32 bytes) and persist it in
 * /data so it survives restarts and updates. A fresh install starts with an
 * empty /data, so every installation gets its own token.
 */
function bootstrapToken(): string {
  try {
    if (existsSync(TOKEN_PATH)) {
      const t = readFileSync(TOKEN_PATH, "utf8").trim();
      if (t) {
        log.info(`API token loaded from ${TOKEN_PATH} (delete this file to force a new one).`);
        log.warning(`API token for your MCP clients: ${t}`);
        return t;
      }
    }
  } catch {
    // fall through to generation
  }
  const t = randomBytes(32).toString("hex");
  try {
    writeFileSync(TOKEN_PATH, t, { mode: 0o600 });
    log.warning(`No api_token configured: a random token was generated and persisted in ${TOKEN_PATH}.`);
  } catch {
    log.warning("No api_token configured and /data is not writable: using an ephemeral token (dev mode).");
  }
  log.warning(`API token for your MCP clients: ${t}`);
  return t;
}
