import { existsSync, readFileSync, renameSync, writeFileSync } from "node:fs";
import { randomBytes } from "node:crypto";
import { z } from "zod";
import { log, setLogLevel } from "./logger.js";
import { maskSecret } from "./safety.js";

export const VERSION = "0.30.0";

const OPTIONS_PATH = "/data/options.json";
const TOKEN_PATH = "/data/token";
/** Below this size a user-chosen token is realistically brute-forceable. */
export const MIN_TOKEN_LENGTH = 16;

/**
 * The full set of accepted tokens: the primary token (always write scope,
 * this is the generated/rotated one) plus the extra named tokens (#85).
 */
export function effectiveTokens(cfg: AddonConfig): ApiToken[] {
  return [{ name: "default", token: cfg.apiToken, scope: "write" }, ...cfg.apiTokens];
}

export type TokenScope = "read" | "write";

export interface ApiToken {
  name: string;
  token: string;
  scope: TokenScope;
}

export interface AddonConfig {
  port: number;
  apiToken: string;
  /** True when the token was generated by us instead of set by the user. */
  apiTokenGenerated: boolean;
  /** Extra named tokens with a scope, on top of the primary api_token (#85). */
  apiTokens: ApiToken[];
  allowWrite: boolean;
  /** Exposes ha_get_camera_snapshot; independent from allowWrite (#86). */
  allowCamera: boolean;
  /** Exposes automation/script creation; independent from allowWrite (#94). */
  allowConfigWrite: boolean;
  /** Long-lived MCP sessions: SSE streams, subscriptions, elicitation (#90). */
  enableSessions: boolean;
  filterReads: boolean;
  entityAllowlist: string[];
  entityDenylist: string[];
  serviceDenylist: string[];
  /** Domains whose writes require the two-step confirmation (v0.2). */
  confirmDomains: string[];
  /** Token injected by the Supervisor when running as an add-on. */
  supervisorToken: string | null;
  /** Dev mode outside the add-on: HA base URL and a long-lived access token. */
  devHaUrl: string | null;
  devHaToken: string | null;
}

/**
 * Runtime validation of /data/options.json. The Supervisor validates against
 * the config.yaml schema, but dev mode has no Supervisor and a corrupted file
 * must degrade to defaults instead of crash-looping the add-on.
 */
const optionsSchema = z
  .object({
    log_level: z.string().default("info"),
    api_token: z.string().default(""),
    allow_write: z.boolean().default(false),
    allow_camera: z.boolean().default(false),
    allow_config_write: z.boolean().default(false),
    enable_sessions: z.boolean().default(false),
    filter_reads: z.boolean().default(false),
    entity_allowlist: z.array(z.string()).default([]),
    entity_denylist: z.array(z.string()).default([]),
    service_denylist: z.array(z.string()).default([]),
    confirm_domains: z.array(z.string()).default(["lock", "alarm_control_panel"]),
    api_tokens: z
      .array(
        z
          .object({
            name: z.string().default("token"),
            token: z.string().default(""),
            scope: z.enum(["read", "write"]).default("write"),
          })
          .loose()
      )
      .default([]),
  })
  .loose();

type Options = z.infer<typeof optionsSchema>;

function readOptions(): Options {
  let raw: unknown = {};
  if (existsSync(OPTIONS_PATH)) {
    try {
      raw = JSON.parse(readFileSync(OPTIONS_PATH, "utf8"));
    } catch (e) {
      log.error(`Could not read ${OPTIONS_PATH}: ${String(e)}. Falling back to defaults.`);
    }
  }
  if (typeof raw !== "object" || raw === null || Array.isArray(raw)) raw = {};
  const parsed = optionsSchema.safeParse(raw);
  if (parsed.success) return parsed.data;
  log.error(
    `Invalid values in ${OPTIONS_PATH} (${parsed.error.issues
      .map((i) => `${i.path.join(".")}: ${i.message}`)
      .join("; ")}). Falling back to defaults.`
  );
  return optionsSchema.parse({});
}

function parsePort(v: string | undefined): number {
  const n = Number(v ?? 9583);
  if (!Number.isInteger(n) || n < 1 || n > 65535) {
    log.warning(`Invalid MCP_PORT value "${v}", using 9583`);
    return 9583;
  }
  return n;
}

export function loadConfig(): AddonConfig {
  const opts = readOptions();

  const level = setLogLevel(String(process.env.LOG_LEVEL ?? opts.log_level));
  log.debug(`Log level set to ${level}`);

  let apiToken = (opts.api_token || process.env.MCP_API_TOKEN || "").trim();
  let apiTokenGenerated = false;
  if (!apiToken) {
    apiToken = bootstrapToken();
    apiTokenGenerated = true;
  } else if (apiToken.length < MIN_TOKEN_LENGTH) {
    // Accepted for now to avoid locking out existing setups, but loudly:
    // a short token on a LAN endpoint is brute-forceable.
    log.error(
      `The configured api_token is only ${apiToken.length} characters long (minimum recommended: ${MIN_TOKEN_LENGTH}). ` +
        "It is realistically brute-forceable; clear the option to get a strong generated token."
    );
  }

  const apiTokens: ApiToken[] = opts.api_tokens
    .filter((t) => t.token.trim().length > 0)
    .map((t) => ({ name: t.name.trim() || "token", token: t.token.trim(), scope: t.scope }));
  for (const t of apiTokens) {
    if (t.token.length < MIN_TOKEN_LENGTH) {
      log.error(`Named api_token "${t.name}" is only ${t.token.length} characters long (minimum recommended: ${MIN_TOKEN_LENGTH}), brute-forceable.`);
    }
  }
  if (apiTokens.length > 0) {
    log.info(`${apiTokens.length} named token(s) configured: ${apiTokens.map((t) => `${t.name}(${t.scope})`).join(", ")}`);
  }

  return {
    port: parsePort(process.env.MCP_PORT),
    apiToken,
    apiTokenGenerated,
    apiTokens,
    allowWrite: opts.allow_write || process.env.MCP_ALLOW_WRITE === "true",
    allowCamera: opts.allow_camera,
    allowConfigWrite: opts.allow_config_write,
    enableSessions: opts.enable_sessions,
    filterReads: opts.filter_reads,
    entityAllowlist: opts.entity_allowlist.filter((s) => s.trim().length > 0),
    entityDenylist: opts.entity_denylist.filter((s) => s.trim().length > 0),
    serviceDenylist: opts.service_denylist.filter((s) => s.trim().length > 0),
    confirmDomains: opts.confirm_domains.filter((s) => s.trim().length > 0),
    supervisorToken: process.env.SUPERVISOR_TOKEN ?? null,
    devHaUrl: process.env.HA_URL ?? null,
    devHaToken: process.env.HA_TOKEN ?? null,
  };
}

/**
 * No token configured: generate a random one (32 bytes) and persist it in
 * /data so it survives restarts and updates. A fresh install starts with an
 * empty /data, so every installation gets its own token.
 *
 * The token is a secret: it never reaches the logs in full, only a masked
 * prefix does. The full value is available in the add-on Configuration tab
 * (the startup write-back saves it into the api_token option).
 */
function bootstrapToken(): string {
  try {
    if (existsSync(TOKEN_PATH)) {
      const t = readFileSync(TOKEN_PATH, "utf8").trim();
      if (t) {
        log.info(
          `API token ${maskSecret(t)} loaded from ${TOKEN_PATH}. The full token is in the add-on Configuration tab (api_token option); delete ${TOKEN_PATH} to force a new one.`
        );
        return t;
      }
    }
  } catch {
    // fall through to generation
  }
  const t = randomBytes(32).toString("hex");
  try {
    // Atomic write: a kill in the middle of a plain write would leave a
    // truncated token and lock every client out after the next boot.
    writeFileSync(`${TOKEN_PATH}.tmp`, t, { mode: 0o600 });
    renameSync(`${TOKEN_PATH}.tmp`, TOKEN_PATH);
    log.warning(
      `No api_token configured: generated ${maskSecret(t)} and persisted it in ${TOKEN_PATH}. Read the full token in the add-on Configuration tab (api_token option).`
    );
  } catch {
    log.warning(
      `No api_token configured and /data is not writable: using an ephemeral token ${maskSecret(t)}. Set MCP_API_TOKEN explicitly to use a known value (dev mode).`
    );
  }
  return t;
}
