import { createServer, type IncomingMessage, type ServerResponse } from "node:http";
import { StreamableHTTPServerTransport } from "@modelcontextprotocol/sdk/server/streamableHttp.js";
import { loadConfig, VERSION, type AddonConfig } from "./config.js";
import { getLogLevel, log } from "./logger.js";
import { safeEqual } from "./safety.js";
import { HaWsClient } from "./ha/ws.js";
import { HaHttp } from "./ha/http.js";
import { Catalog } from "./ha/catalog.js";
import { buildServer } from "./mcp/server.js";
import type { ToolContext } from "./context.js";

const MAX_BODY_BYTES = 4_000_000;

function readJsonBody(req: IncomingMessage): Promise<unknown> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    let size = 0;
    req.on("data", (c: Buffer) => {
      size += c.length;
      if (size > MAX_BODY_BYTES) {
        reject(new Error("request body too large"));
        req.destroy();
        return;
      }
      chunks.push(c);
    });
    req.on("end", () => {
      if (chunks.length === 0) return resolve(undefined);
      try {
        resolve(JSON.parse(Buffer.concat(chunks).toString("utf8")));
      } catch {
        reject(new Error("invalid JSON"));
      }
    });
    req.on("error", reject);
  });
}

function sendJson(res: ServerResponse, status: number, body: unknown, headers: Record<string, string> = {}): void {
  res.writeHead(status, { "Content-Type": "application/json", ...headers });
  res.end(JSON.stringify(body));
}

function rpcError(res: ServerResponse, status: number, code: number, message: string, headers: Record<string, string> = {}): void {
  sendJson(res, status, { jsonrpc: "2.0", error: { code, message }, id: null }, headers);
}

/**
 * When the token was generated by us, write it back into the add-on options
 * so it becomes visible and editable in the HA configuration panel instead
 * of hiding in the logs. Best effort: a failure only logs a warning.
 */
async function persistGeneratedToken(cfg: AddonConfig, http: HaHttp): Promise<void> {
  if (!cfg.apiTokenGenerated || !http.supervisorAvailable) return;
  try {
    const info = await http.supervisorGet("/addons/self/info");
    const options = { ...(info?.options ?? {}), api_token: cfg.apiToken };
    await http.supervisorPost("/addons/self/options", { options });
    log.notice("Generated API token saved into the add-on options (visible in the HA configuration panel).");
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    log.warning(`Could not save the generated token into the add-on options: ${msg}`);
  }
}

async function main(): Promise<void> {
  const cfg = loadConfig();

  const ws = new HaWsClient(cfg);
  ws.connect();
  const http = new HaHttp(cfg);
  const ctx: ToolContext = { cfg, ws, http, catalog: new Catalog(ws) };
  void persistGeneratedToken(cfg, http);

  const httpServer = createServer(async (req, res) => {
    const url = new URL(req.url ?? "/", "http://localhost");

    if (url.pathname === "/health" && req.method === "GET") {
      // Unauthenticated on purpose and deliberately minimal: nothing
      // sensitive in here.
      sendJson(res, 200, { status: "ok", version: VERSION, websocket: ws.connected });
      return;
    }

    if (url.pathname !== "/mcp") {
      sendJson(res, 404, { error: "not found" });
      return;
    }

    if (req.method !== "POST") {
      rpcError(res, 405, -32000, "method not allowed, this server is stateless (POST only)", {
        Allow: "POST",
      });
      return;
    }

    const auth = req.headers.authorization ?? "";
    const match = auth.match(/^Bearer\s+(.+)$/i);
    if (!match || !safeEqual(match[1].trim(), cfg.apiToken)) {
      log.notice(`Unauthorized MCP request from ${req.socket.remoteAddress ?? "unknown"}`);
      rpcError(res, 401, -32001, "unauthorized", { "WWW-Authenticate": "Bearer" });
      return;
    }

    try {
      const body = await readJsonBody(req);
      log.debug(`MCP request from ${req.socket.remoteAddress ?? "unknown"}`);
      // Stateless mode: one server and one transport per request, no session.
      const server = buildServer(ctx);
      const transport = new StreamableHTTPServerTransport({
        sessionIdGenerator: undefined,
        enableJsonResponse: true,
      });
      res.on("close", () => {
        transport.close();
        server.close();
      });
      await server.connect(transport);
      await transport.handleRequest(req, res, body);
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      log.warning(`MCP request failed: ${msg}`);
      if (!res.headersSent) rpcError(res, 400, -32700, msg);
      else res.end();
    }
  });

  httpServer.listen(cfg.port, "0.0.0.0", () => {
    log.info(`mcp-ha ${VERSION} listening on port ${cfg.port} (MCP endpoint /mcp, health /health)`);
    log.info(`Mode: ${cfg.supervisorToken ? "add-on (Supervisor)" : "dev (HA_URL)"}`);
    log.info(`Log level: ${getLogLevel()}`);
    log.info(`Write access (allow_write): ${cfg.allowWrite ? "ENABLED, ha_call_service is exposed" : "disabled, read only"}`);
    if (cfg.filterReads) log.info("filter_reads is active: the denylist also applies to reads.");
  });

  const stop = (): void => {
    log.info("Shutdown requested, closing...");
    httpServer.close();
    ws.shutdown();
    process.exit(0);
  };
  process.on("SIGTERM", stop);
  process.on("SIGINT", stop);
}

main().catch((e) => {
  log.fatal(`Startup failed: ${e instanceof Error ? e.stack ?? e.message : String(e)}`);
  process.exit(1);
});
